### ISSUE TITLE
Pre-emptive libc version woe

### ISSUE THREAD

**Issue by itowlson** [itowlson/spin-pluginify#13]
This project currently builds on `ubuntu-latest`.  In other projects, we've found this causes problems for folks on Debian or Ubuntu 20, because it causes a dependency on a later version of libc.  We should generally prefer to do builds on Ubuntu 20.04.

**Comment by karthik2804** [comment]
Just ran into it 😅 .https://github.com/fermyon/spin-trigger-cron/actions/runs/8471879771/job/23212801452?pr=13
